# Generated by Django 5.2.4 on 2025-08-26 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name': '科室', 'verbose_name_plural': '科室'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['emp_id'], 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='科室名称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='emp_id',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='工号'),
        ),
    ]
