# Generated by Django 5.2.4 on 2025-08-26 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_department_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='科室名称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='emp_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='工号'),
        ),
    ]
