# Generated by Django 5.2.4 on 2025-08-05 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RelicLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, verbose_name='国家')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='地区')),
                ('institution', models.CharField(max_length=200, verbose_name='收藏机构')),
                ('count', models.IntegerField(verbose_name='敦煌文物数量')),
                ('digitized_percent', models.FloatField(default=0, verbose_name='数字化进度')),
                ('publication', models.TextField(blank=True, verbose_name='相关出版物')),
                ('source', models.TextField(blank=True, verbose_name='数据来源')),
            ],
        ),
        migrations.CreateModel(
            name='RelicLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_note', models.TextField(verbose_name='改动说明')),
                ('change_reason', models.TextField(blank=True, verbose_name='改动原因')),
                ('old_count', models.IntegerField(verbose_name='原数量')),
                ('new_count', models.IntegerField(verbose_name='新数量')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relicmap.reliclocation')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
