# Generated by Django 5.2.4 on 2025-08-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relicmap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reliclocation',
            name='digitized_percent',
            field=models.FloatField(default=0, verbose_name='数字化百分比'),
        ),
    ]
