# Generated by Django 5.2.4 on 2025-07-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Outbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='资料名称')),
                ('category', models.CharField(choices=[('book', '图书'), ('photo', '照片'), ('manuscript', '手稿'), ('other', '其它')], max_length=20, verbose_name='资料种类')),
                ('pages', models.IntegerField(blank=True, null=True, verbose_name='页数')),
                ('platen', models.CharField(choices=[('flat', '平板'), ('vshape', 'V型板')], max_length=10, verbose_name='扫描设备')),
                ('color_paper', models.BooleanField(default=False, verbose_name='是否需要色纸')),
                ('condition', models.TextField(blank=True, verbose_name='出库书况登记')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('out_time', models.DateTimeField(auto_now_add=True, verbose_name='出库时间')),
                ('taken_at', models.DateTimeField(blank=True, null=True, verbose_name='承接时间')),
            ],
        ),
        migrations.CreateModel(
            name='QualityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiff_complete', models.BooleanField(verbose_name='TIFF图片完整')),
                ('jpeg_consistent', models.BooleanField(verbose_name='JPEG图片一致')),
                ('pdf_assembled', models.BooleanField(verbose_name='是否合成PDF')),
                ('ocr_done', models.BooleanField(verbose_name='是否完成OCR')),
                ('ocr_score', models.IntegerField(verbose_name='OCR处理评分')),
                ('data_intact', models.BooleanField(verbose_name='数据存储完整性')),
                ('inspected_at', models.DateTimeField(auto_now_add=True, verbose_name='检验时间')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=12, unique=True, verbose_name='批次号')),
                ('start_time', models.DateTimeField(verbose_name='数字化开始时间')),
                ('title', models.CharField(max_length=200, verbose_name='题名信息')),
                ('other_title', models.CharField(blank=True, max_length=200, verbose_name='其它题名信息')),
                ('main_responsibility', models.CharField(blank=True, max_length=100, verbose_name='主要责任者')),
                ('other_responsibility', models.CharField(blank=True, max_length=100, verbose_name='其它责任者')),
                ('pub_place', models.CharField(blank=True, max_length=100, verbose_name='出版地')),
                ('publisher', models.CharField(blank=True, max_length=100, verbose_name='出版者')),
                ('pub_year', models.CharField(blank=True, max_length=10, verbose_name='出版年')),
                ('total_pages', models.IntegerField(verbose_name='总页数')),
                ('doc_type', models.CharField(blank=True, max_length=50, verbose_name='文献类型标识')),
                ('registered_at', models.DateTimeField(verbose_name='登记日期')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
            ],
        ),
    ]
