# Generated by Django 5.2.4 on 2025-07-28 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('digitization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='outbound',
            name='librarian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='登记人'),
        ),
        migrations.AddField(
            model_name='outbound',
            name='taken_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taken_outbounds', to=settings.AUTH_USER_MODEL, verbose_name='承接人'),
        ),
        migrations.AddField(
            model_name='qualitycheck',
            name='inspector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='检验人'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='数字化负责人员'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='out_bound',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='digitization.outbound', verbose_name='对应出库单'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='registrar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registered_workorders', to=settings.AUTH_USER_MODEL, verbose_name='登记人员'),
        ),
        migrations.AddField(
            model_name='qualitycheck',
            name='work_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='digitization.workorder', verbose_name='对应工作单'),
        ),
    ]
