# Generated by Django 5.2.4 on 2025-08-04 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitization', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitizationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='资料名称')),
                ('category', models.CharField(max_length=20, verbose_name='资料种类')),
                ('pages', models.IntegerField(blank=True, null=True, verbose_name='页数')),
                ('platen', models.CharField(max_length=10, verbose_name='扫描设备')),
                ('color_paper', models.BooleanField(default=False, verbose_name='需要色纸')),
                ('condition', models.TextField(blank=True, verbose_name='出库书况登记')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='题名信息')),
                ('other_title', models.CharField(blank=True, max_length=200, verbose_name='其它题名信息')),
                ('main_responsibility', models.CharField(blank=True, max_length=100, verbose_name='主要责任者')),
                ('other_responsibility', models.CharField(blank=True, max_length=100, verbose_name='其它责任者')),
                ('pub_place', models.CharField(blank=True, max_length=100, verbose_name='出版地')),
                ('publisher', models.CharField(blank=True, max_length=100, verbose_name='出版者')),
                ('pub_year', models.CharField(blank=True, max_length=10, verbose_name='出版年')),
                ('total_pages', models.IntegerField(blank=True, null=True, verbose_name='总页数')),
                ('doc_type', models.CharField(blank=True, max_length=50, verbose_name='文献类型标识')),
                ('tiff_complete', models.BooleanField(default=False, verbose_name='TIFF图片完整')),
                ('jpeg_consistent', models.BooleanField(default=False, verbose_name='JPEG一致')),
                ('pdf_assembled', models.BooleanField(default=False, verbose_name='PDF已合成')),
                ('ocr_done', models.BooleanField(default=False, verbose_name='OCR完成')),
                ('ocr_score', models.IntegerField(blank=True, null=True, verbose_name='OCR评分')),
                ('data_intact', models.BooleanField(default=False, verbose_name='数据完整性')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='digitizations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
