# Generated by Django 5.2.4 on 2025-08-04 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitization', '0003_digitizationform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DigitizationForm',
        ),
    ]
