# Generated by Django 5.2.4 on 2025-08-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitization', '0004_delete_digitizationform'),
    ]

    operations = [
        migrations.AddField(
            model_name='outbound',
            name='is_returned',
            field=models.BooleanField(default=False, verbose_name='是否已入库'),
        ),
        migrations.AddField(
            model_name='outbound',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='入库时间'),
        ),
    ]
