# Generated by Django 5.2.4 on 2025-08-05 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filebox', '0002_uploadedfile_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filecategory',
            options={'verbose_name': '文件分类', 'verbose_name_plural': '文件分类'},
        ),
        migrations.AddField(
            model_name='filecategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='filebox.filecategory'),
        ),
    ]
