# Generated by Django 5.2.4 on 2025-08-26 03:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='流程名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='流程编码')),
                ('description', models.TextField(blank=True, default='', verbose_name='说明')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '流程模板',
                'verbose_name_plural': '流程模板',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NodeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='节点名称')),
                ('code', models.CharField(max_length=50, verbose_name='节点编码')),
                ('node_type', models.CharField(choices=[('start', '开始'), ('approve', '审批'), ('end', '结束')], default='approve', max_length=20, verbose_name='节点类型')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='顺序')),
                ('assigned_group_name', models.CharField(blank=True, default='', max_length=100, verbose_name='处理用户组名')),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='指定用户')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='flow.processtemplate', verbose_name='所属流程')),
            ],
            options={
                'verbose_name': '节点模板',
                'verbose_name_plural': '节点模板',
                'ordering': ['process', 'order'],
                'unique_together': {('process', 'code')},
            },
        ),
        migrations.CreateModel(
            name='NodeInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrived_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='到达时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('status', models.CharField(default='pending', max_length=20, verbose_name='状态')),
                ('handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_nodes', to=settings.AUTH_USER_MODEL, verbose_name='实际处理人')),
                ('node_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flow.nodetemplate', verbose_name='节点模板')),
            ],
            options={
                'verbose_name': '节点实例',
                'verbose_name_plural': '节点实例',
            },
        ),
        migrations.CreateModel(
            name='ProcessInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('status', models.CharField(default='running', max_length=20, verbose_name='状态')),
                ('current_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='flow.nodeinstance', verbose_name='当前节点')),
                ('starter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='started_processes', to=settings.AUTH_USER_MODEL, verbose_name='发起人')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='flow.processtemplate', verbose_name='流程模板')),
            ],
            options={
                'verbose_name': '流程实例',
                'verbose_name_plural': '流程实例',
            },
        ),
        migrations.AddField(
            model_name='nodeinstance',
            name='process_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='flow.processinstance', verbose_name='流程实例'),
        ),
        migrations.CreateModel(
            name='Binding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='业务对象ID')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='业务模型类型')),
                ('process_instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='binding', to='flow.processinstance', verbose_name='流程实例')),
            ],
            options={
                'verbose_name': '流程绑定',
                'verbose_name_plural': '流程绑定',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='flow_bindin_content_caeecf_idx')],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('status', models.CharField(default='open', max_length=20, verbose_name='状态')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('node_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='flow.nodeinstance', verbose_name='节点实例')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
                'indexes': [models.Index(fields=['assignee', 'status'], name='flow_task_assigne_f796ee_idx')],
            },
        ),
    ]
