# Generated by Django 5.2.4 on 2025-08-26 08:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=64, verbose_name='节点编码')),
                ('name', models.CharField(max_length=200, verbose_name='节点名称')),
                ('type', models.CharField(choices=[('start', '开始'), ('task', '任务'), ('approval', '审批'), ('gateway', '网关'), ('end', '结束')], default='task', max_length=16, verbose_name='节点类型')),
                ('assignees', models.JSONField(default=list, verbose_name='指派规则')),
                ('allow_claim', models.BooleanField(default=False, verbose_name='是否抢单模式（组内认领）')),
                ('form_overrides', models.JSONField(default=dict, verbose_name='表单覆盖/权限')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='表单名称')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('json_schema', models.JSONField(default=dict, verbose_name='JSON Schema')),
                ('ui_schema', models.JSONField(default=dict, verbose_name='UI Schema')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='nodeinstance',
            name='handler',
        ),
        migrations.RemoveField(
            model_name='nodeinstance',
            name='node_template',
        ),
        migrations.RemoveField(
            model_name='nodeinstance',
            name='process_instance',
        ),
        migrations.RemoveField(
            model_name='processinstance',
            name='current_node',
        ),
        migrations.RemoveField(
            model_name='task',
            name='node_instance',
        ),
        migrations.AlterUniqueTogether(
            name='nodetemplate',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='nodetemplate',
            name='assigned_user',
        ),
        migrations.RemoveField(
            model_name='nodetemplate',
            name='process',
        ),
        migrations.RemoveField(
            model_name='processinstance',
            name='process',
        ),
        migrations.RemoveField(
            model_name='processinstance',
            name='starter',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assignee',
        ),
        migrations.CreateModel(
            name='FlowInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('running', '运行中'), ('completed', '已完成'), ('terminated', '已终止')], default='running', max_length=16, verbose_name='状态')),
                ('form_data', models.JSONField(default=dict, verbose_name='表单数据')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='实例标题')),
                ('starter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_instances', to=settings.AUTH_USER_MODEL, verbose_name='发起人')),
                ('current_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_instances', to='flow.flownode', verbose_name='当前节点')),
            ],
            options={
                'verbose_name': '流程实例',
                'verbose_name_plural': '流程实例',
            },
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=64, verbose_name='动作')),
                ('payload', models.JSONField(default=dict, verbose_name='载荷')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='flow.flowinstance', verbose_name='实例')),
                ('node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flow.flownode', verbose_name='节点')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
            },
        ),
        migrations.CreateModel(
            name='FlowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='模板编码')),
                ('name', models.CharField(max_length=200, verbose_name='模板名称')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '启用'), ('archived', '归档')], default='draft', max_length=16, verbose_name='状态')),
                ('version', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='版本号')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_flow_templates', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flow_templates', to='flow.formschema', verbose_name='主表单')),
            ],
            options={
                'verbose_name': '流程模板',
                'verbose_name_plural': '流程模板',
            },
        ),
        migrations.AddField(
            model_name='flownode',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='flow.flowtemplate', verbose_name='所属模板'),
        ),
        migrations.AddField(
            model_name='flowinstance',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='flow.flowtemplate', verbose_name='模板'),
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='流转名称')),
                ('condition', models.TextField(blank=True, verbose_name='条件表达式')),
                ('priority', models.IntegerField(default=100, verbose_name='优先级（数字越小越先匹配）')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_transitions', to='flow.flownode', verbose_name='来源节点')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_transitions', to='flow.flownode', verbose_name='目标节点')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='flow.flowtemplate', verbose_name='所属模板')),
            ],
            options={
                'verbose_name': '流转边',
                'verbose_name_plural': '流转边',
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignees', models.JSONField(default=list, verbose_name='候选处理人')),
                ('status', models.CharField(choices=[('open', '待处理'), ('claimed', '已认领'), ('done', '已完成'), ('canceled', '已取消')], default='open', max_length=16, verbose_name='状态')),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='到期时间')),
                ('action', models.CharField(blank=True, max_length=64, verbose_name='处理动作')),
                ('comment', models.TextField(blank=True, verbose_name='处理意见')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_items', to='flow.flowinstance', verbose_name='所属实例')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_items', to='flow.flownode', verbose_name='节点')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_work_items', to=settings.AUTH_USER_MODEL, verbose_name='当前处理人')),
            ],
            options={
                'verbose_name': '待办/工作项',
                'verbose_name_plural': '待办/工作项',
            },
        ),
        migrations.DeleteModel(
            name='Binding',
        ),
        migrations.DeleteModel(
            name='NodeInstance',
        ),
        migrations.DeleteModel(
            name='NodeTemplate',
        ),
        migrations.DeleteModel(
            name='ProcessTemplate',
        ),
        migrations.DeleteModel(
            name='ProcessInstance',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
