# Generated by Django 5.2.4 on 2025-08-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0002_flownode_formschema_remove_nodeinstance_handler_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formschema',
            name='json_schema',
            field=models.JSONField(blank=True, default=dict, verbose_name='JSON Schema'),
        ),
        migrations.AlterField(
            model_name='formschema',
            name='ui_schema',
            field=models.JSONField(blank=True, default=dict, verbose_name='UI Schema'),
        ),
    ]
