# Generated by Django 5.2.4 on 2025-08-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0003_alter_formschema_json_schema_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flownode',
            name='assignees',
            field=models.JSONField(blank=True, default=list, verbose_name='指派规则'),
        ),
        migrations.AlterField(
            model_name='flownode',
            name='form_overrides',
            field=models.JSONField(blank=True, default=dict, verbose_name='表单覆盖/权限'),
        ),
    ]
