# Generated by Django 5.2.4 on 2025-08-26 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0004_alter_flownode_assignees_and_more'),
        ('users', '0003_alter_department_options_alter_user_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flownode',
            options={'ordering': ['id'], 'verbose_name': '流程节点', 'verbose_name_plural': '流程节点'},
        ),
        migrations.AddField(
            model_name='flownode',
            name='assigned_departments',
            field=models.ManyToManyField(blank=True, related_name='flow_assigned_nodes', to='users.department', verbose_name='指派科室（可多选）'),
        ),
        migrations.AddField(
            model_name='flownode',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='flow_assigned_nodes', to=settings.AUTH_USER_MODEL, verbose_name='指派用户（可多选）'),
        ),
        migrations.AlterField(
            model_name='flownode',
            name='assignees',
            field=models.JSONField(blank=True, default=list, verbose_name='[废弃] 指派规则(JSON)'),
        ),
        migrations.AlterField(
            model_name='flownode',
            name='form_overrides',
            field=models.JSONField(blank=True, default=dict, verbose_name='[废弃] 表单覆盖/权限(JSON)'),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='assignees',
            field=models.JSONField(blank=True, default=list, verbose_name='候选处理人'),
        ),
        migrations.AlterUniqueTogether(
            name='flownode',
            unique_together={('template', 'code')},
        ),
        migrations.CreateModel(
            name='NodeFieldRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_name', models.CharField(max_length=100, verbose_name='字段名')),
                ('hidden', models.BooleanField(default=False, verbose_name='隐藏')),
                ('readonly', models.BooleanField(default=False, verbose_name='只读')),
                ('required', models.BooleanField(default=False, verbose_name='必填')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_rules', to='flow.flownode', verbose_name='节点')),
            ],
            options={
                'verbose_name': '字段权限规则',
                'verbose_name_plural': '字段权限规则',
                'unique_together': {('node', 'field_name')},
            },
        ),
    ]
