# Generated by Django 5.2.4 on 2025-08-27 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0005_alter_flownode_options_flownode_assigned_departments_and_more'),
        ('users', '0003_alter_department_options_alter_user_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormDef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='表单名称')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
            ],
            options={
                'verbose_name': '表单定义',
                'verbose_name_plural': '表单定义',
            },
        ),
        migrations.RemoveField(
            model_name='flowtemplate',
            name='form',
        ),
        migrations.AlterField(
            model_name='flownode',
            name='allow_claim',
            field=models.BooleanField(default=False, verbose_name='是否抢单模式'),
        ),
        migrations.AlterField(
            model_name='flownode',
            name='assigned_departments',
            field=models.ManyToManyField(blank=True, related_name='flow_assigned_nodes', to='users.department', verbose_name='指派科室'),
        ),
        migrations.AlterField(
            model_name='flownode',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='flow_assigned_nodes', to=settings.AUTH_USER_MODEL, verbose_name='指派用户'),
        ),
        migrations.AddField(
            model_name='flowtemplate',
            name='form_def',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flow_templates', to='flow.formdef', verbose_name='主表单'),
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=64, verbose_name='字段名（英文字母/下划线）')),
                ('title', models.CharField(max_length=200, verbose_name='字段标题')),
                ('type', models.CharField(choices=[('string', '文本'), ('integer', '整数'), ('number', '小数'), ('boolean', '布尔'), ('text', '多行文本'), ('select', '下拉单选'), ('date', '日期'), ('datetime', '日期时间')], default='string', max_length=16, verbose_name='类型')),
                ('required', models.BooleanField(default=False, verbose_name='必填')),
                ('options', models.TextField(blank=True, verbose_name='下拉选项（每行一项，仅当类型=下拉单选）')),
                ('order', models.PositiveIntegerField(default=100, verbose_name='显示顺序（小在前）')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='flow.formdef', verbose_name='所属表单')),
            ],
            options={
                'verbose_name': '表单字段',
                'verbose_name_plural': '表单字段',
                'ordering': ['order', 'id'],
                'unique_together': {('form', 'name')},
            },
        ),
    ]
