# Generated by Django 5.2.4 on 2025-08-05 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('leave', '请假'), ('overtime', '加班')], max_length=10, verbose_name='类型')),
                ('start_date', models.DateField(verbose_name='开始时间')),
                ('end_date', models.DateField(verbose_name='结束时间')),
                ('duration', models.FloatField(help_text='请假单位为天，加班单位为小时', verbose_name='时长')),
                ('leave_type', models.CharField(blank=True, choices=[('sick', '病假'), ('personal', '事假'), ('annual', '年假'), ('other', '其它')], max_length=20, verbose_name='请假类型')),
                ('leave_reason', models.TextField(blank=True, verbose_name='请假事由')),
                ('overtime_reason', models.TextField(blank=True, verbose_name='加班事由')),
                ('overtime_place', models.CharField(blank=True, max_length=100, verbose_name='加班地点')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registrar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registered_attendance', to=settings.AUTH_USER_MODEL, verbose_name='登记人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='记录人员')),
            ],
            options={
                'permissions': [('can_manage_attendance', '可管理考勤记录')],
            },
        ),
    ]
