# Generated by Django 5.2.4 on 2025-08-05 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='user',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='person_name',
            field=models.CharField(default='未知人员', max_length=50, verbose_name='请假人员 / 加班人员'),
        ),
    ]
